version: '3.3'

services:
  postgresql:
   container_name: postgresql
   image: postgres:latest
   env_file:
    - config/db/env
   networks:
    - "bookapi"
   volumes:
   # Mount volume int.sql vào thư mục trong container
   # Đối với version 3.3, khi mount file vào container cần có thêm ./ phía trước folder cần mount. còn đối với version 3 thì không cần tiền tố ./
    - "./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
   # Mount thư mục data trong container ra ngoài host - Cụ thể là folder được tạo ngay trên thư mục project có tên là postgresql
    - "./postgresql:/var/lib/postgresql/data"
  book-service:
   container_name: book-service
   build:
    context: ./
    dockerfile: Dockerfile
   env_file:
    - "config/app/.env"
   depends_on: 
    - postgresql
   ports:
    - "8000:8080"
   networks:
    - "bookapi"
volumes: {}
networks:
  bookapi:
   name: bookapi
   driver: bridge