version: '3.3'

services:
  postgresql:
   container_name: postgresql
   image: postgres:latest
   env_file:
    - config/db/env
   networks:
    - "bookapi"
   volumes:
    - "./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql"
    - "./postgresql:/var/lib/postgresql/data"
  book-service:
   container_name: book-service
   build:
    context: ./
    dockerfile: Dockerfile
   env_file:
    - "config/app/.env"
   depends_on: 
    - postgresql
   ports:
    - "8000:8080"
   networks:
    - "bookapi"
volumes: {}
networks:
  bookapi:
   name: bookapi
   driver: bridge