version: '3.3'

services:
  db:
   container_name: db
   image: mysql:5.7
   networks:
    - "ghost-network"
   environment:
    - "MYSQL_ROOT_PASSWORD=example"
   volumes:
    - "ghost-vol:target=/var/lib/mysql"
  ghostblog:
   container_name: ghostblog
   image: ghost:alpine
   networks:
    - "ghost-network"
   ports:
    - "80:2368"
   environment:
    - "database_client=mysql"
    - "database_connection_host=db"
    - "database_connection_user=root"
    - "database_connection_password=example"
    - "database_connection_database=ghost"
volumes: {}
networks:
  ghost-network:
   name: ghost-network
   driver: bridge