version: '3.3'

services:
 mongodb:
  container_name: mongodb
  image: mongo:latest
  volumes:
    - ./mongodb:/data/db
  networks:
   - "nodejsmongo"
networks:
 nodejsmongo:
  name: nodejsmongo
  driver: bridge